### ISSUE TITLE
True North Position

### ISSUE THREAD

**Issue by Michele404** [ProjectDent/ARKit-CoreLocation#119]
How can I get the real true north position?
I disable the automatic check of true north and I have created a compass that when its calibrated it start the session. The user , before start the session, should point the true north but how can I determine where is the true north and how can I Pass the calibration to AR?

**Comment by intere** [comment]
@Michele404 - if this is fixed by https://github.com/ProjectDent/ARKit-CoreLocation/pull/125, could you please close this issue?

**Comment by Michele404** [comment]
Not fixxed

**Comment by intere** [comment]
@Michele404 - this is likely due to the following:
1. A lack of location accuracy - typically the accuracy is bad when location services start up and get more accurate as a better signal is picked up and your position is triangulated
2. True north error that's described in the readme and a hardware (or at least OS-level) limitation
