### ISSUE TITLE
Help updating label using buildViewNode.

### ISSUE THREAD

**Issue by elga2** [ProjectDent/ARKit-CoreLocation#155]
Added some text nodes using buildViewNode but now struggling to update the text with distance from current position. Can anyone suggest how this might work?

**Comment by Sibaiur** [comment]
Currently having the same problem. Did you find out how to do it?

**Comment by intere** [comment]
That's currently a limitation.  In https://github.com/ProjectDent/ARKit-CoreLocation/pull/176, I've changed the implementation that takes a UIView to convert it to an image before adding it as a node (so the view has zero chance of ever updating in the scene).  This is by design, if you want to update the image of the node, I recommend updating the node image directly or using some other method (e.g. a label in the app instead of an element in the AR Scene).
