### ISSUE TITLE
Incorrect argument label in call (have 'location:view:', expected 'location:image:')

### ISSUE THREAD

**Issue by bcheco** [ProjectDent/ARKit-CoreLocation#165]
Hello,

I am currently attempting to use version 1.0.4, I am attempt to implement the function 

```
func buildViewNode(latitude: CLLocationDegrees, longitude: CLLocationDegrees, altitude: CLLocationDistance, text: String) -> LocationAnnotationNode {
        let coordinate = CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
        let location = CLLocation(coordinate: coordinate, altitude: altitude)
        let label = UILabel(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
        label.text = text
        label.backgroundColor = .green
        return LocationAnnotationNode(location: location, view: label)
    }
```

As shown in the example but am receiving the error of `Incorrect argument label in call (have 'location:view:', expected 'location:image:')` with the suggestion of `Replace 'view' with 'image'`. Any ideas as to why this could be?

**Comment by aaronbrethorst** [comment]
v1.0.4 does not have the init method that you are looking for. Point to `master` instead of the `1.0.4` release you're using until we can cut a new cocoapod. 

Code at this release: https://github.com/ProjectDent/ARKit-CoreLocation/blob/aee28dd81dbf49dc8a435eddaf999aa573ab3fa7/ARCL/Source/LocationNode.swift

Follow #163 to know when this release occurs.
