### ISSUE TITLE
Carthage won't build using the develop branch

### ISSUE THREAD

**Issue by atbreuer11** [ProjectDent/ARKit-CoreLocation#186]
Carthage throws the following error when building from the develop branch. However, using the master branch Carthage is able to build the package successfully.  

<img width="884" alt="Screen Shot 2019-05-20 at 4 27 00 PM" src="https://user-images.githubusercontent.com/6656197/58050405-45649b00-7b1d-11e9-9922-679a8a3aa54a.png">

Cartfile:
github "ProjectDent/ARKit-CoreLocation" "develop"

**Comment by intere** [comment]
@atbreuer11 - have you made any headway on this?  I'd happily review a PR that addresses this.  I don't / haven't ever used Carthage and I'm not sure I'd be the best resource to help here.

**Comment by DerekK19** [comment]
It's actually quite straightforward to fix this. The Xcode schemes would need to have at least one shared scheme. Click on the scheme selector and choose Manage Schemes.... In the resulting dialog, use the right-hand check box to set the required scheme as shared.

This would be a good thing to fix, then the project would be Carthage compliant. It also wouldn't use trouble for most non-carthage developers

In my case I have taken a copy of the code and included the files in my project, because I have modified the code in some places (not a good thing to do)

**Comment by xeokeri** [comment]
I'm running into the same issue. Can verify it's still happening.

```
*** Skipped building ARKit-CoreLocation due to the error:
Dependency "ARKit-CoreLocation" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/ProjectDent/ARKit-CoreLocation/issues/new
```

Tried with master, 1.3.0, and others. All the same.
