### ISSUE TITLE
locationNodeTouched(node: AnnotationNode) node.view is nil

### ISSUE THREAD

**Issue by justbane** [ProjectDent/ARKit-CoreLocation#210]
Hi there - using ARCL 1.2.0

I have added the LNTouchDelegate to my view controller

I have added the locationNodeTouched function

I am using the LocationAnnotationNode(location: location, view: plaque) - plaque is a subclass of UIView

I receive the touches just fine but the node.view is always nil. I can see my plaques in the scene and if I touch one I get the node item in the function but its view component is nil.

```
func locationNodeTouched(node: AnnotationNode) {
        // Do stuffs with the node instance
        
        // node could have either node.view or node.image
        if let nodeView = node.view { // <-- node.view is always nil
            // Do stuffs with the nodeView
            // ...
        }
    }

```

**Comment by intere** [comment]
This is by design.  There was an expectation that when a view repaints, the scene would be updated, but that just doesn't happen.  See https://github.com/ProjectDent/ARKit-CoreLocation/pull/176 for more details, but having a view in the ARSCNView caused some pretty big issues and it didn't update in the scene when the view repainted, so I opted to change it so that it merely creates an image from the view and uses that. 🤷‍♂
