### ISSUE TITLE
After pausing and leaving the ViewController and then returning and running, the heading of the scene shifts.

### ISSUE THREAD

**Issue by chrisiKern** [ProjectDent/ARKit-CoreLocation#25]
With `orientToTrueNorth` activated, the scenes heading seems to move about 90°.

**Comment by chrisiKern** [comment]
Ok, not necessarily 90°, it seems a bit unpredictable to me.

**Comment by chrisiKern** [comment]
It seems to depend a lot on where I'm looking when i return to the ViewController with the sceneLocationView.

**Comment by chatwyn** [comment]
Hi, Did you solve the problem?

**Comment by chrisiKern** [comment]
@chatwyn No, sorry, I personally haven't.

**Comment by JacoGasp** [comment]
I have the same problem and I believe it's related somehow to the fact the `viewDidDisappear` and `viewWillDisappear`  are not fired and the sceneLocationView is not closed properly

**Comment by dappledore-hotkey** [comment]
i have the same problem, the only way i could fix it was by recreating the scenelocationview when the app is restored but then i have to recreate the pins.

**Comment by MaticConradi** [comment]
You should restart the scene. I've made my own implementation since it seems like it isn't possible in this framework.

**Comment by pareekkhushboo77** [comment]
@MaticConradi , @dappledore-hotkey @JacoGasp @chatwyn @chrisiKern  can anyone of you please let me know what code you have written in viewwillAppear and viewWillDisappear, as i am not able to overcome this bug. Please it would be really great if you can help.
Thanks.

**Comment by MaticConradi** [comment]
The only thing I do in viewWillAppear and viewWillDissappear is running/stopping the session. That’s it. I configure all the nodes in the viewDidLoad.

**Comment by pareekkhushboo77** [comment]
Oh, instead of .pause you do .stop at viewWillDissappear, 
thanks for your response :)

**Comment by MaticConradi** [comment]
Right, but how... ARKit session doesn’t have a stop() method, does it?

**Comment by pareekkhushboo77** [comment]
Yes it does have, but i havent tried, will try that now.

**Comment by sungjin0213** [comment]
Even if I'm recreating nodes after resuming the view, the  heading of the scene shifts. Anybody had solution to this?

**Comment by AakashSareen** [comment]
@sungjin0213 did you go through the comments in SceneLocationView.swift.  The author explains the situation. The hint is that that the user should be aligned to true north , a make sure you add your scene after yo have reasonable approximation of trueNorth. Afterwards, we have two methods to shift scene heading.(clockwise and anti-clockwise), these are the corrections you should apply as you get more accurate north, or you could just ask user to orient phone to north before adding. You would need to build this around your use case and do the correction. 

I've been working on a project that required AR objects based on surfaces as well as GPS. Keep in mind 
``` configuration.worldAlignment = .gravityAndHeading``` 
aligns the world such world -z axes is aligned to north and -y along the phone (direction downwards)

Now apple may update the origin of the coordinate system of the AR world, once it has a better understanding of true north. 

Another gotcha moment is that Heading readings can be inaccurate (due to magnetic fields from TV etc IIRC), so one solution would be show some into stuff till you get a reall good estimate of north, ask the user to orient to north and then add the scene, 

It would be so much easier, if SceneLocationView was a protocol, and we had the flexibility of using apple's sub class of ARSCNView as it has the object addition/interaction/update/deletion designed very robustly.

**Comment by intere** [comment]
Closing this issue - it's old and stale.

**Comment by Lelelo1** [comment]
When I tried out ARKit ago year I tried `configuration.worldAlignment = .gravityAndHeading` it gave a local coordinate system in the orientation, meaning when it is started, it always gives 0 heading in that direction. Given from the responses here it seems problem where never resolved?
