### ISSUE TITLE
How can I get the 2nd Gif effect?

### ISSUE THREAD

**Issue by liming8964** [ProjectDent/ARKit-CoreLocation#81]
I am using your library in my AR iOS app project.

I want to make the navigation effect by the address in ar mode like your 2nd Gif(Starbucks navigation).
I have checked this source code but I can't find this effect.

Please help me.
Best regards.

**Comment by ProjectDent** [comment]
MapKit APIs give you a set of coordinates for a directions search. ARKit+CoreLocation takes coordinates, so you can draw a path using those.

**Comment by scm573** [comment]
Hi,

I have the same question. Specifically about the drawing part.
Now we have the coordinates, get the route from MapKit, then how should we draw the route? I'd like to know the suggested way to achieve that.
And another concern is, since this project(library) is already using MapKit, can it provide such feature that can directly draw the polyline in the 3D scene? I think it should be quite a common requirement.

**Comment by scm573** [comment]
I found there was such an extension file could help draw the polyline, great!

[https://github.com/ProjectDent/ARKit-CoreLocation/blob/feature/mapkit/ARKit%2BCoreLocation/SceneLocationView%2BAddLikeMapKit.swift](url)

**Comment by imJunaidAbd** [comment]
The link you posted doesn’t work
